### ISSUE TITLE
tree_size is getting doubled somewhere in state_table[source]

### ISSUE THREAD

**Issue by PhishingAI** [d3vzer0/faust-transparency#1]
Something is causing states_table[source] to double which in turn causes this to stop working...
        elif stats['tree_size'] > states_table[source]:

I printed the two values and the states_table[source] is almost exactly double the real value every time... 

166999869(*2) = 333999738

333999738-333991004= 8734

8734 is about the number I'm expecting to see:

2019-04-22 15:27:55,391: WARNING]: stats['tree_size'] : 166999869  states_table[source]: 333991004 
[2019-04-22 15:27:55,391: WARNING]: stats['tree_size'] : 444760  states_table[source]: 889519 
[2019-04-22 15:27:55,457: WARNING]: stats['tree_size'] : 661921109  states_table[source]: 1323826762 
[2019-04-22 15:27:55,689: WARNING]: stats['tree_size'] : 152008834  states_table[source]: 304017495

**Comment by d3vzer0** [comment]
Ah silly me, I made a small mistake by adding the last value PLUS the newly seen value (instead of just the difference or latest value). Ill make the change and push it in an hour :)

**Comment by d3vzer0** [comment]
I removed the unnecessary addition to the counter. The issue should be solved now :) There does seem to be an issue that a timeout can occur when trying to reach a transparency source. This could cause the agent to restart. I'll have to look into this issue later as well.

<img width="987" alt="Screenshot 2019-04-23 at 11 34 59" src="https://user-images.githubusercontent.com/34250156/56570842-fd089a80-65bb-11e9-87b3-af852dce4b4a.png">
